{
  "uuid": "e39bcda5-8316-48f9-9a4a-f4b82f6bf1c5",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "cd1faf90-9c2e-439d-b3a1-f6a7a95cb3df"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1757482699124,
  "stop": 1757482712420
}